@startuml
box main
collections client as C
participant "//compute//" as G #lightblue
end box
queue "queue\nmax **M**" as Q #lightblue
box listener
participant listener as L #lightblue
participant "executor\n**N×**" as E #lightblue
end box
collections task as T #lightgreen

C -> G : compute
activate G
G -> Q : add
activate Q
loop queue listener
L -> Q: **take**
deactivate Q
activate L
L -> E : **execute**
deactivate L
activate E
end
E -> T : run
deactivate E
activate T
G -> G : get
activate G #gold
T --> G: result
deactivate T
G --> G: value
deactivate G
G -> C :  value
deactivate G
@enduml